[build]
  publish = "."

[[redirects]]
  from = "/sheet-html"
  to = "https://docs.google.com/spreadsheets/d/e/2PACX-1vSod7Mdzh3NW4a8uyA1cXEF51Clo-8I1KapKosN5-XgOyqXMWYoQ31_vdM53RhGJn_s6m8ETxNeTjqi/pubhtml"
  status = 200
  force = true

[[headers]]
  for = "/sheet-html"
  [headers.values]
    Cache-Control = "no-store, max-age=0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
